CREATE TABLE ATG_3696_INSP_H(
 INSP_NO IDENTITY DEFAULT '0',
 WO CHAR(6) NOT NULL ,
 SUFFIX CHAR(3) NOT NULL ,
 SEQ CHAR(6) NOT NULL ,
 INSP_DATE DATETIME NOT NULL ,
 EMP_NO CHAR(5) NOT NULL ,
 EMP_NAME CHAR(30) NOT NULL ,
 WC CHAR(4) NOT NULL ,
 WC_DESC CHAR(20),
 PART_NO CHAR(20) NOT NULL ,
 PART_DESC CHAR(30)
);