CREATE TABLE ATG_3696_INSP_L(
 INSP_NO INTEGER NOT NULL ,
 SEQ INTEGER NOT NULL ,
 SAMPLE_ID CHAR(2) NOT NULL ,
 TYPE_LOC CHAR(10) NOT NULL ,
 REQ_DIM FLOAT NOT NULL ,
 TOL FLOAT NOT NULL ,
 ACT_DIM FLOAT NOT NULL ,
 GAUGE INTEGER NOT NULL ,
 ACPT_REJ CHAR(1) NOT NULL ,
 NOTES VARCHAR(50)
);